### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by jroto** [tihonav/cad-to-geant4-converter#1]
Hi @tihonav,

I'm trying to use your software to convert some geometry in CAD to GDML. I ran successfully the example, but when I try to run my geometry, the generated GDML files does not contain any geometry, and I get the following message:
`Could not parse material for the file 311selection.stl: - asigning Vacuum to this volume!` 
My CAD files doesn't contain material info, but I guess the geometry should be generated anyway, right?
Also, what is the format needed for the material information? How I can include this? I'm sorry if this is too obvious, I'm just a newcomer.

Thank you in advance,
J.

**Comment by tihonav** [comment]
Hi,

For your first question:
```could not parse material for the file 311selection.stl: - asigning Vacuum to this volume!```
Event though it didn't recognize the material, it should still create a GDML file with the Vacuum material assigned to a volume. 
  - To debug the problem, could you please attach (or send) your ```311selection.stl``` file?
  - Could you please quote the exact command that you used to convert this file?

Next, if you want to assign the material, you should simply out the name of the material in the stl file, for example ```my_volume1_Silicon.stl```. For more information and list of currently implemented, see https://github.com/tihonav/cad-to-geant4-converter/blob/master/README.md#materials. 

Cheers,
Andrii

**Comment by jroto** [comment]
Hi Andrii,

The command I use is: `python ../stl_gdml.py 311geo ./311selection.stl`
Since the stl file is bit heavy, I upload it to [cernbox](https://cernbox.cern.ch/index.php/s/EctKLOkS2u2KDVn). 
I'm using FreeCAD to create it, just selecting some parts of a more general STP file, and exporting it as a STL.

About assigning the material, thank you, it is really clear in the guide, now it recognise the material.

Thanks for your help!
J.

**Comment by tihonav** [comment]
Hello J,

Thanks for the details. I've checked the ```311selection.stl``` file, it seems it is in the binary STL format. 
That is, two types of STL format exists:
  - ASCII STL
  - Binary STL
(see https://en.wikipedia.org/wiki/STL_(file_format)).

The converter supports the ASCII STL, which is human readable and looks approximately like this:
```
solid CATIA STL
  facet normal  3.981976e-001 -3.981976e-001 -8.263641e-001
    outer loop
      vertex -4.024131e+002 -4.421275e+002  6.645833e+001
      vertex -4.092353e+002 -4.480332e+002  6.601675e+001
      vertex -4.028713e+002 -4.416693e+002  6.601675e+001
    endloop
  endfacet
....
```
see for exmple: https://raw.githubusercontent.com/tihonav/cad-to-geant4-converter/master/Example/DAM_EQM_CornerAluminum.stl


I think in FreeCad there should be a possibility to create ASCII STL instead of binary. You can also check out some online services that produce STL files, for example http://www.3dtransform.com/.

Cheers,
Andrii

**Comment by jroto** [comment]
Hi Andrii,
Now it works! For the record, the way to export in ASCII STL format, is using the termination ".ast", and then change it to ".stl".
Thank you!
J.

**Comment by tihonav** [comment]
Hi J,

Great to hear, and thanks a lot for the useful information.
I will a corresponding instruction to the documentation, based on you experience with stl.

Cheers,
Andrii
