### ISSUE TITLE
issue with the viewer

### ISSUE THREAD

**Issue by jroto** [tihonav/cad-to-geant4-converter#4]
Hi,
The load_gdml viewer stopped working... It was really usefull, do you know how I can set it up again?
source /afs/cern.ch/work/a/andrii/public/GDML/setup_geant4_gdml_xerces.sh doesn't seem to work anymore.

Cheers,
J.

**Comment by tihonav** [comment]
Hi,

Just checked the example 2 in https://github.com/tihonav/cad-to-geant4-converter#examples

 ... and everything worked fine, including:     
   /afs/cern.ch/work/a/andrii/public/GDML/setup_geant4_gdml_xerces.sh   
and  
    load_gdml

Could you please provide more details ?

Cheers,
Andrii

**Comment by jroto** [comment]
Hi,
This is the output of my terminal running in a lxplus machine:

[jsotooto@lxplus084 fieldshaper]$ source /afs/cern.ch/work/a/andrii/public/GDML/setup_geant4_gdml_xerces.sh
Setting python2.7..
Setting GCC..
Setting geant4..
Setting xerces
[jsotooto@lxplus084 ~]$ load_gdml 
-bash: load_gdml: command not found
[jsotooto@lxplus084 ~]$ 

After sourcing the script, it does not even find the command when I tab... Before it was working fine, I don't know what happened...

Thanks for your help!

J.

**Comment by tihonav** [comment]
Hi,

load_gdml   is not defined  in the setup_geant4_gdml_xerces.sh.  

You need to copy the corresponding Geant4 basic example and compile it:

**********
cp -r /afs/cern.ch/sw/lcg/external/geant4/9.6.p03/share/examples/extended/persistency/gdml/G01 ~/
cd ~/G01
make
**********


Then it will work. For details, see "Get and compile GEANT4 gdml example" in https://github.com/tihonav/cad-to-geant4-converter#examples

Hope this helps,
Andrii

**Comment by jroto** [comment]
You are right. That works. Thanks!
